### ISSUE TITLE
[Request] New content descriptors for disturbing content

### ISSUE THREAD

**Issue by KirbyJoe** [dnaf/OGRS#10]
Hello,

I can't find the content descriptors for disturbing content that implemented on many other rating system across the world.
Many horror games at Game Jolt (which uses a customized OGRS rating system) doesn't have any content descriptors about these, and I don't know why OGRS doesn't have a content descriptors for a "disturbing content".
When you (dnaf) implement them into a OGRS Rating system, please tell me a reason why the content descriptors of disturbing content aren't implemented.

Sincely,
KirbyJoe(JoeH)

**Comment by k80w** [comment]
Added, thanks for the recommendation! ^-^

Also, I was unaware that GameJolt was using OGRS. It's really cool seeing my project's name on such a big website. I didn't know anyone else really used it at all!

**Comment by KirbyJoe** [comment]
Hello? I can’t find a “Disturbing Content” on the generator, it’s maybe a glitch. Here’s an issue for detail of that with addition of levels: https://github.com/dnaf/OGRS/issues/11
